# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-08-20 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20200725_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='small_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
